# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
            ],
            options={
                'verbose_name_plural': 'Заказчики',
                'verbose_name': 'Заказчик',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=100, verbose_name='Имя поставщика')),
            ],
            options={
                'verbose_name_plural': 'Поставщики',
                'verbose_name': 'Поставщик',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100, verbose_name='Регион')),
            ],
            options={
                'verbose_name_plural': 'Регионы',
                'verbose_name': 'Регион',
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='regions_provider',
            field=models.ManyToManyField(to='orders.Region', verbose_name='Регион поставщика'),
        ),
        migrations.AddField(
            model_name='client',
            name='regions_client',
            field=models.ManyToManyField(to='orders.Region', verbose_name='Регион заказчика'),
        ),
    ]
